version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: auth-system
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: auth
    ports:
      - '5439:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
